### ISSUE TITLE
首次启动报错，不知道该怎么解决

### ISSUE THREAD

**Issue by tjcfnerd** [curtinlv/gd#37]
asyncio ERROR [default_exception_handler] Task exception was never retrieved
future: <Task finished name='Task-10' coro=<hello() done, defined at /ql/data/jbot/__main__.py:71> exception=ValueError('Could not find the input entity for PeerUser(user_id=2096307281) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.')> 
Traceback (most recent call last):
  File "/ql/data/jbot/__main__.py", line 76, in hello
    await jdbot.send_message(chat_id, f'{str(hello_word)}\n\n\t{info}', link_preview=False)
  File "/usr/lib/python3.9/site-packages/telethon/client/messages.py", line 810, in send_message
    entity = await self.get_input_entity(entity)
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 466, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerUser(user_id=2096307281) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

**Comment by cairong** [comment]
同故障，同问

**Comment by tjcfnerd** [comment]
换了2.12.2版本ql已正常
